- name: Install MariaDB 
  dnf: 
    name: "{{ packages_mariadb }}"
    state: latest

- name: Started and Enabled MariaDB
  service: 
    name: mariadb 
    enabled: true 
    state: started 

- name: Configurations root password for MariaDB
  mysql_user:
    check_implicit_admin: true
    login_user: root 
    login_password: "{{ mysql_root_pass }}"
    user: root 
    password: "{{ mysql_root_pass }}"
    host: localhost 

- name: Create DataBase nextcloud
  community.mysql.mysql_db:
    name: "{{ name_db }}"
    encoding: utf8
    collation: utf8_bin
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Create User nextcloud
  community.mysql.mysql_user:
    name: "{{ user_db }}"
    password: "{{ pass_user_db }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"